apiVersion: v1
kind: Pod
metadata:
  name:  single-pod
  labels:
    zone: Production
    version: v1
spec:
  containers:
    - image: harbor.kay.local/library/k8s:latest
      name:  node-pod
      ports:
        - containerPort: 3000