# for version below 1.24
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: '*'
  name: vrops-read-only
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs:
  - /
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vrops-mp-read-only-user
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vrops-mp-read-only-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vrops-read-only
subjects:
  - kind: ServiceAccount
    name: vrops-mp-read-only-user
    namespace: default


    # Post applying above yaml file using kubectl apply -f <filename>.yaml, below token provides the bearer token. 
    # $(kubectl get secret $(kubectl get serviceaccount  vrops-mp-read-only-user -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}' | base64 --decode )
    
